on: push
name: deploy
jobs:
  build-push-dockerhub:
    name: build and push devrik99/strapi-bingx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build an push to dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            devrik99/strapi-bingx:latest
            devrik99/strapi-bingx:${{ github.sha }}
  deploy-to-portainer:
    needs: [build-push-dockerhub]
    name: deploy to portainer
    runs-on: ubuntu-latest
    steps:
      - uses: devrik99/portainer-stack-deploy@master
        with:
          serverurl: http://54.37.139.100:9000
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          access_token: ${{secrets.ACCESS_TOKEN}}
          endpointId: 2
          #stackname: strapi-bingx
          docker_compose: |
            version: "3"
            services:
              strapi-bingx:
                container_name: "strapi-bingx"
                environment:
                  DATABASE_CLIENT: mysql
                  JWT_SECRET: UPdeMGSKkpmzzHnpovCFfw==
                  DATABASE_HOST: 54.37.139.100
                  DATABASE_PORT: "3306"  # Puertos deben ser strings entre comillas si no se utilizan en variables de entorno.
                  DATABASE_NAME: strapi-bingx
                  DATABASE_USERNAME: devrik
                  DATABASE_PASSWORD: vIHn&E3Wmasz
                  APP_KEYS: s6wCpknAbH5+3GsX4Uj9+A==,93ZHardtayWkTPa6pL1vrA==,2EG7l1K6MZ1/8lPH4rW+7g==,pwYRWoVOn0UYKthD7kWnzg==
                  API_TOKEN_SALT: XGLjqkzV/eKtgBBXIABxzg==
                  ADMIN_JWT_SECRET: 2agwOrZ0DF2FqwYxGu08NA==
                  TRANSFER_TOKEN_SALT: hvXfpeaJi/avmzZaqYMIGg==
                  stackname: strapi-bingx
                restart: always
                ports:
                  - "1337:1337"
                image: devrik99/strapi-bingx:latest
